name: r_w # responsive Web(responsive)
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0 # from version 1.0.0 of universal

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  country_flags: ^3.0.0
  condora_automatic_getter_storage_directory: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  package_rename: ^1.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

# Run 'dart run package_rename' in the terminal to apply the new package information
package_rename_config:
  web:
    app_name: WW # (String) The title of the web app and PWA
    short_app_name: # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: Web Boilerplate for automatic configuration of navigation # (String) The description of the web app and PWA
