name: responsive_bottomnavigation_navigationrail
description: "A boilerplate Flutter project for mobile for a responsive bottomnavigation navigationrail depending on the rotation of the device."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.5
  dynamic_storage_directory: ^1.0.0
  path_provider: ^2.1.5
  flutter_bloc: ^8.1.6
  country_flags: ^3.0.0
  condora_automatic_getter_storage_directory: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  package_rename: ^1.7.1

flutter:
  generate: true
  uses-material-design: true

# Run 'dart run package_rename' in the terminal to apply the new package information
# MRBR = Mobile Responsive Bottomnavigation Navigationrail
package_rename_config:
  android:
    app_name: MRBR # (String) The display name of the android app
    package_name: it.ilcondora.mrbr # (String) The package name of the android app
    override_old_package: com.example.responsive_bottomnavigation_navigationrail # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: kotlin # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: MRBR # (String) The display name of the ios app
    bundle_name: mrbr # (String) The bundle name of the ios app, maximum length should be 15 characters
    package_name: it.ilcondora.mrbr # (String) The product bundle identifier of the ios app

